# 生产环境配置
server:
  port: 18080

spring:
  application:
    name: ai-roleplay-backend-prod
  
  # 生产环境数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/ai_roleplay?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&autoReconnect=true
    username: roleplay
    password: roleplay123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    
  # 生产环境Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: -1
      
  # 通义千问AI配置
  ai:
    dashscope:
      # 使用环境变量配置API密钥
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        enabled: true
        options:
          model: qwen-plus
          temperature: 0.7
          top-p: 0.8
          max-tokens: 2000

# 可选：OSS配置
aliyun:
  oss:
    enabled: ${ALIYUN_OSS_ENABLED:false}  # 默认禁用，如需启用设置环境变量
    endpoint: ${ALIYUN_OSS_ENDPOINT:}
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID:}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:}
    bucket-name: ${ALIYUN_OSS_BUCKET_NAME:}

# 日志配置
logging:
  level:
    root: INFO
    com.carol.backend: INFO
    com.alibaba.dashscope: WARN
    org.springframework.ai: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/backend/backend.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 3GB

# 文件上传配置
spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 20MB

# 跨域配置
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  max-age: 3600

